# Generated by Django 5.1.7 on 2025-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(height_field='300', upload_to='profile_image', width_field='300'),
        ),
    ]
