# Generated by Django 5.1.7 on 2025-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='about/')),
                ('background', models.TextField()),
                ('teamwork', models.TextField()),
                ('our_core_value', models.TextField()),
            ],
        ),
    ]
